package try_catch_block_exceptions_programs;

public class Try_Catch_BlockExample1 {
	public static void main(String[] args) {
		//if we run the code we get arithmetic exception
		int data=100/0;
		//rest of the code
		System.out.println("This is remaining code");
	}
}
